package uz.pdp.common.enums;

public enum TypeTextState {
    DEFAULT,
    WRITE_DESCRIPTION,
    WRITE_ID_FOR_DELETE,
    WRITE_REMINDER_ID_FOR_DELETE,

    WRITE_REMINDER_DESCRIPTION,
    WRITE_REMINDER_TIME,
    WRITE_ONCE_DESCRIPTION,
    WRITE_ONCE_DATE,
    WRITE_CERTAIN_DESCRIPTION,
    WRITE_CERTAIN_DATE
}
